version: '3'
services:
  app:
    container_name: ians-mongo
    restart: always
    build:
      context: ./Users/iancampbell/Desktop/Muhib/Node/vidly
    ports:
      - '5500:5500'
    external_links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27012:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8083:8081'
